### ISSUE TITLE
Connect to Photoneo device from another service in Docker-compose file

### ISSUE THREAD

**Issue by MBL-DGS** [photoneo/phoxi-docker#2]
### Solution:
The main repository shows an example on how to define the docker file and docker-compose file. If you want to connect to the PhoXiControl contrainer, you have to additionally share the ```/opt``` folder as well as the  ``` /dev/shm``` folder with the corresponding services. 

Below i have attached the ```docker-compose.yaml``` file.

``` 
version: "3.6"

services:
  phoxicontrol:
    build:
      context: ./PhoXiControl_custom/context
      dockerfile: $PWD/PhoXiControl_custom/Dockerfile.PhoXiControl
      # args:
      #   buildno: 1
    image: photoneo/phoxicontrol:latest
    devices:
      - /dev/dri:/dev/dri
    volumes:
      - /tmp/.X11-unix/:/tmp/.X11-unix
      - /var/run/dbus:/var/run/dbus
      - /dev/shm:/dev/shm
      - phoxicontrol_opt:/opt        
    privileged: true
    environment:
      - DISPLAY
      - DOCKER=1
      - QT_X11_NO_MITSHM=1
      - SHELL
    stop_signal: SIGKILL
    security_opt:
      - apparmor=unconfined
    logging:
      driver: journald
      options:
        tag: '{{.ImageID}}/{{.Name}}/{{.ID}}'

  custom-application:
    build:
      context: ./custom_application/ 
      dockerfile: $PWD/custom-application/Dockerfile.custom
    volumes:
      - phoxicontrol_opt:/opt        
      - /dev/shm:/dev/shm

volumes:  
  phoxicontrol_opt:                 
    external: False  # Use an external volume  
```
